export const candidateProfile = {
  name: "Luis Angel Diaz Diaz",
  targetRoles: [
    "devops",
    "cloud engineer",
    "platform engineer",
    "site reliability",
    "sre",
    "backend",
    "node.js",
    "typescript",
    "frontend",
    "react",
    "full stack",
    "fullstack",
    "web developer",
    "infrastructure engineer",
    "software engineer",
    "software developer"
  ],
  preferredLevels: [
    "junior",
    "jr",
    "entry level",
    "entry-level",
    "intern",
    "internship",
    "trainee",
    "graduate",
    "becario",
    "practicante"
  ],
  excludedLevels: [
    "senior",
    "sr.",
    "sr ",
    "lead",
    "principal",
    "staff",
    "director",
    "head of",
    "staff engineer",
    "manager",
    "architect"
  ],
  allowedLocations: [
    "mexico",
    "méxico",
    "oaxaca",
    "latin america",
    "latam",
    "americas",
    "worldwide",
    "anywhere",
    "global",
    "remote"
  ],
  skills: [
    { name: "Docker", aliases: ["docker", "containerization", "containers"] },
    { name: "Docker Compose", aliases: ["docker compose", "docker-compose"] },
    { name: "Kubernetes", aliases: ["kubernetes", "k8s", "k3s", "kubebuilder"] },
    { name: "CI/CD", aliases: ["ci/cd", "continuous integration", "github actions", "jenkins"] },
    { name: "Linux", aliases: ["linux", "fedora", "debian", "ubuntu"] },
    { name: "Node.js", aliases: ["node.js", "nodejs", "node js", "express"] },
    { name: "TypeScript", aliases: ["typescript"] },
    { name: "JavaScript", aliases: ["javascript"] },
    { name: "React", aliases: ["react", "react.js", "reactjs", "next.js", "nextjs"] },
    { name: "PostgreSQL", aliases: ["postgresql", "postgres", "sql"] },
    { name: "MongoDB", aliases: ["mongodb", "mongo"] },
    { name: "Git", aliases: ["git", "github", "gitlab"] },
    { name: "Cloudflare", aliases: ["cloudflare", "cloudflare tunnel"] },
    { name: "RabbitMQ", aliases: ["rabbitmq", "message broker", "amqp"] },
    { name: "MinIO", aliases: ["minio", "s3 compatible", "object storage"] },
    { name: "REST APIs", aliases: ["rest api", "restful", "api development"] }
  ],
  highlightedSkills: ["Docker", "Kubernetes", "CI/CD", "Linux", "Node.js", "TypeScript", "React"],
  searchQueries: ["devops junior", "cloud junior", "backend node typescript", "frontend react junior"]
} as const;
